### ISSUE TITLE
This plugin does not work anymore

### ISSUE THREAD

**Issue by hason** [stecman/composer-bash-completion-plugin#8]
The plugin is not loaded due to this commit https://github.com/composer/composer/commit/0627d846a5a4b4378ad74851d877c3f5f34a6aaa

**Comment by stecman** [comment]
Thanks @hason - I noticed the plugin had stopped working a few weeks ago but hadn't got around to fixing it.

That change to Composer means that completion has to be piggy-backed onto another command, so the hooks have changed slightly to call `composer depends _completion` instead of `composer _completion`.
